name: Build ESP32

on:
  push:
    branches:
      - develop_vn
  workflow_dispatch:
  

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: espressif/idf:release-v5.5

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build project
        run: |
          . $IDF_PATH/export.sh
          idf.py set-target esp32s3
          idf.py build
