name: Build ESP32

on:
  push:
    branches:
      - develop_vn
  workflow_dispatch:
  

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: espressif/idf:release-v5.5

    steps:
      - name: Check ESP-IDF
        run: |
          echo "IDF_PATH=$IDF_PATH"
          ls $IDF_PATH

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build project
        run: |
          . $IDF_PATH/export.sh
          idf.py set-target esp32s3
          idf.py build

      - name: Set timestamp
        run: echo "TS=$(date +"%y%m%d.%H%M")" >> $GITHUB_ENV

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/firmware-${{ env.TS }}.bin
